### ISSUE TITLE
Broccoli part 1 is 404

### ISSUE THREAD

**Issue by techtonik** [troch/troch.github.io#4]
http://blog.reactandbethankful.com/posts/2015/07/11/building-with-broccoli-part-1-presentation/
linked from
http://blog.reactandbethankful.com/posts/2015/04/18/tour-of-node-building-tools/

**Comment by troch** [comment]
Thanks for reporting it, it has been fixed. Correct link is: http://blog.reactandbethankful.com/posts/2015/07/11/building-with-broccoli-part-1-introduction/
