### ISSUE TITLE
Missing detail at "Understanding the functional revolution in front-end applications"

### ISSUE THREAD

**Issue by justincorrigible** [troch/troch.github.io#7]
Great article! I do have to ask, in this case how does .map normalise the array with apparently no action done?

It is going through the array (much like using a `for` on it, but it seems to me like there's no callback to normalise anything —i.e. nothing is done to the array. Am I misreading your example?

``` js
Let me show you a brief example of a mapReduce operation: it first normalises an array (map), and adds up its values (reduce).

function sumArray(values) {
    return values
        .map(Number)
        .reduce((total, value) => total + value);
}

sumArray([1, '2', '30']); // 33
```

If I get it accordingly, this could well be shown as:

``` js
Let me show you a brief example of a reduce operation: it adds up its values.

function sumArray(values) {
    return values.reduce((total, value) => total + value);
}

sumArray([1, '2', '30']); // 33
```

Is that right? or am I missing something?

**Comment by troch** [comment]
`values.map(Number)` creates a new array from `values`, with all values normalised to numbers. `Number` is a function, which means you can write it that way rather than `values.map((val) => Number(val))`

It is a dumb example of mapReduce. It could well be contracted in a single reduce example but the point is not to show a map and a reduce together.

**Comment by justincorrigible** [comment]
Hmm I knew I must've been missing something. Even though I understand what you mean, I'm not used to the syntax you're using (calling the function without parenthesis after it, is that a react/jsx thing?). Where could I find documentation on this?

**Comment by troch** [comment]
> I'm not used to the syntax you're using (calling the function without parenthesis

`.map()` takes a function reference, `Number` is a function.

> is that a react/jsx thing?

Not at all.

> Where could I find documentation on this?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number#Convert_numeric_strings_to_numbers

**Comment by justincorrigible** [comment]
Oh I've meant using `Number`without the `()` to summon it. But I may have just needed some coffee. LOL thanks

Great article.
